import { useEffect, useRef, useState } from 'react';
import type { ReactNode, PointerEvent } from 'react';
import { motion, useMotionValue, useSpring, useReducedMotion } from 'framer-motion';
import Lenis from 'lenis';
import { X, ArrowUpRight } from 'lucide-react';
import { projects, email } from './data';

export function Reveal({children,className=''}:{children:ReactNode,className?:string}){const reduced=useReducedMotion();return <motion.div className={className} initial={reduced?false:{opacity:0,y:25}} whileInView={{opacity:1,y:0}} viewport={{once:true,amount:.12}} transition={{duration:.7,ease:[.22,1,.36,1]}}>{children}</motion.div>}
export function Tilt({children,className=''}:{children:ReactNode,className?:string}){const reduced=useReducedMotion();const x=useMotionValue(0),y=useMotionValue(0);const rx=useSpring(x,{stiffness:160,damping:23}),ry=useSpring(y,{stiffness:160,damping:23});function move(e:PointerEvent<HTMLDivElement>){if(reduced||e.pointerType!=='mouse')return;const r=e.currentTarget.getBoundingClientRect();x.set(-((e.clientY-r.top)/r.height-.5)*10);y.set(((e.clientX-r.left)/r.width-.5)*10);e.currentTarget.style.setProperty('--spot-x',`${e.clientX-r.left}px`);e.currentTarget.style.setProperty('--spot-y',`${e.clientY-r.top}px`);}return <motion.div className={`tilt ${className}`} style={{rotateX:rx,rotateY:ry,transformPerspective:1000}} onPointerMove={move} onPointerLeave={()=>{x.set(0);y.set(0)}}>{children}<div className="spotlight"/></motion.div>}
export function AmbientEffects({reduced}:{reduced:boolean}){const x=useMotionValue(-100),y=useMotionValue(-100);const sx=useSpring(x,{stiffness:300,damping:35}),sy=useSpring(y,{stiffness:300,damping:35});const[hover,setHover]=useState(false);useEffect(()=>{if(reduced)return;const lenis=new Lenis({duration:1.1,smoothWheel:true,anchors:true});let frame=0;function raf(t:number){lenis.raf(t);frame=requestAnimationFrame(raf);}frame=requestAnimationFrame(raf);return()=>{cancelAnimationFrame(frame);lenis.destroy();}},[reduced]);useEffect(()=>{if(reduced||!matchMedia('(pointer:fine)').matches)return;const move=(e:globalThis.PointerEvent)=>{x.set(e.clientX-14);y.set(e.clientY-14);setHover(!!(e.target as Element).closest('a,button,input,textarea'));};window.addEventListener('pointermove',move);return()=>window.removeEventListener('pointermove',move);},[reduced,x,y]);return reduced?null:<motion.div className={`cursor ${hover?'hover':''}`} style={{x:sx,y:sy}} aria-hidden="true"/>}
export function Modal({children,title,onClose,className=''}:{children:ReactNode,title:string,onClose:()=>void,className?:string}){const ref=useRef<HTMLDialogElement>(null);useEffect(()=>{const d=ref.current;const previous=document.activeElement as HTMLElement;d?.showModal();document.body.style.overflow='hidden';return()=>{d?.close();document.body.style.overflow='';previous?.focus();};},[]);return <dialog ref={ref} className={`modal ${className}`} aria-label={title} onCancel={e=>{e.preventDefault();onClose();}} onClick={e=>{if(e.target===e.currentTarget){const r=e.currentTarget.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)onClose();}}}><div className="modal-bar"><span>{title}</span><button className="icon-button" onClick={onClose} aria-label="Close dialog"><X size={20}/></button></div>{children}</dialog>}
export function TerminalWindow({onClose,onTheme}:{onClose:()=>void,onTheme:()=>void}){const[value,setValue]=useState('');const[history,setHistory]=useState([{command:'',output:'NIKKY OS v1.0 — Welcome to my corner of the internet.\nType help to explore. No technical experience needed.'}]);const output=useRef<HTMLDivElement>(null);useEffect(()=>{output.current?.scrollTo({top:output.current.scrollHeight});},[history]);function run(command:string){const cmd=command.trim().toLowerCase();setValue('');if(cmd==='clear'){setHistory([]);return;}if(cmd==='exit'){onClose();return;}let result='';if(cmd==='help')result='about / cat about.txt → Meet Nikky\nprojects / ls projects → Explore my work\nskills → My toolkit\ncontact → Let’s connect\ntheme → Toggle blueprint mode\nclear → Clear the terminal\nexit → Return to the portfolio';else if(cmd==='about'||cmd==='cat about.txt')result='Niketha Thavaneswaran (Nikky)\nB.Sc. (Hons) Computer Science undergraduate\nUniversity of Vavuniya, Sri Lanka\nCurious about Python, machine learning, software and meaningful data.';else if(cmd==='projects'||cmd==='ls projects')result=projects.map((p,i)=>`${String(i+1).padStart(2,'0')}  ${p.title} — ${p.category}`).join('\n');else if(cmd==='skills')result='Python · Java · HTML · CSS · PHP · MySQL\nPandas · NumPy · Matplotlib · Scikit-learn\nMIPS Assembly · Git · Jupyter · Google Colab';else if(cmd==='contact')result=`Email: ${email}\nGitHub: github.com/tniketha\nLocation: Jaffna, Sri Lanka\nOpen to internships and collaborations.`;else if(cmd==='theme'){onTheme();result='Blueprint mode toggled.';}else if(cmd)result=`Command not found: ${command}. Type help for available commands.`;if(cmd)setHistory(h=>[...h,{command,output:result}]);}return <Modal title="TERMINAL / NIKKY OS" onClose={onClose} className="terminal-modal"><div className="terminal-output" ref={output} aria-live="polite">{history.map((h,i)=><div key={i}>{h.command&&<p className="gold">nikky@portfolio ~ % {h.command}</p>}<pre>{h.output}</pre></div>)}</div><form className="terminal-input" onSubmit={e=>{e.preventDefault();run(value)}}><label htmlFor="command">~ %</label><input id="command" value={value} onChange={e=>setValue(e.target.value)} placeholder="Type a command…" autoComplete="off" autoFocus/><button aria-label="Run command"><ArrowUpRight size={18}/></button></form><div className="terminal-hints">{['help','projects','about','skills'].map(c=><button key={c} onClick={()=>run(c)}>{c}</button>)}<span>ESC TO CLOSE</span></div></Modal>}
export function Boot(){const[show,setShow]=useState(()=>{try{return !sessionStorage.getItem('nikky-boot')}catch{return true}});useEffect(()=>{if(!show)return;const timer=setTimeout(()=>{setShow(false);try{sessionStorage.setItem('nikky-boot','1')}catch{/* Storage is optional. */}},1700);return()=>clearTimeout(timer)},[show]);return show?<div className="boot" aria-hidden="true"><span className="boot-logo">N<span>↗</span></span><p>NIKKY / INITIALIZING EXPERIENCE</p><div className="boot-line"/><small>LOADING CURIOSITY…</small><button onClick={()=>setShow(false)}>Skip intro ↗</button></div>:null}
